const D=[
{a:'Tuomiokirkonkatu 17',x:61.49835,y:23.76756,n:'Sticky Wingers',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Tuomiokirkonkatu%20-%20panoramio.jpg?width=1200',credit:'Wikimedia Commons · 2009',refOnly:true,s:'Yksi keskustan tiheimmistä ravintola- ja yökerhohistorioista.',v:[['Maxim','1970-luku',1970,1979],['Senssi Club 17','1980-luvun loppu',1987,1990],['Nykyaika','1990-luku',1990,1999],['Diva','1990-luku',1990,1999],['Mocca','vuosituhannen alku',2000,2003],['The Club','2004–',2004,2008],['Sticky Wingers','2011–',2011,2026]]},
{a:'Kirkkokatu 10',x:61.49734,y:23.75651,n:'Kauppaseuran talo',img:'https://www.ruokakulttuuri.fi/wp-content/uploads/2022/04/kirkkokatu_masu-clava_ulkoa.jpg',credit:'Jani Kinnunen · Ruoka & Kulttuuri · 2022',src:'https://www.ruokakulttuuri.fi/kirkkokatu-10-viinia-ilman-ehtoollista-vuodesta-1953/',beforeImg:'https://commons.wikimedia.org/wiki/Special:FilePath/August%20Krook,%20Kauppaseuran%20talo,%20Laukontori%204,%20Tampere.jpg?width=1400',beforeCredit:'Museovirasto / Wikimedia Commons · CC BY 4.0',s:'Kauppaseuran talossa on ollut ravintolatoimintaa rakennuksen valmistumisesta 1953 lähtien.',v:[['Kauppaseuran Ravintola','1953–',1953,1979],['Cabare Oscar','1980-luku – 1990-luvun alku',1980,1992],['Cotton Club','Cabare Oscarin aikaan',1980,1992],['Los Americanos','1990-luvun alku',1990,1993],['Crazy Horse','1993–',1993,1999],['Sokeri','Crazy Horsen jälkeen',1999,2005],['Clava','2021–',2021,2026]]},
{a:'Puutarhakatu 21',x:61.49942,y:23.75189,n:'Puutarhakadun liiketalo',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Puutarhakadun%20liiketalo%2C%20N%C3%A4silinnankatu%2022%2C%20Tampere.jpg?width=1200',credit:'Wikimedia Commons · paikannuskuva',refOnly:true,s:'Puutarhakatu 21:n historiaan mahtuu tanssiravintoloita, klubeja ja yökerhoja usealta vuosikymmeneltä.',v:[['Tanssikeskus Simpukka','1970-luku',1970,1979],['Haarikka','1980-luku',1980,1989],['Bat Club','1980-luvun loppupuoli',1987,1990],['City Rock Café','1990-luvun alku',1990,1993],['L.A. Garage','1990-luvun keskivaihe',1993,1997],['Pulse','2000-luvun alku',2000,2004],['Onnela','2000-luvun keskivaihe',2004,2009],['Tivoli','2010-luvun alku',2010,2014],['Hehku','2010-luvun puoliväli',2014,2018]]},
{a:'Hämeenkatu 10',x:61.49809,y:23.76391,n:'Voiman talo',img:'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meenkatu%2010%20in%20Tampere%2020121120%20001.jpg?width=1200',credit:'Mikko J. Putkonen · Wikimedia Commons · 2012',beforeImg:'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meenkatu%2010%20in%20Tampere%20Nov2010%20001b.jpg?width=1200',beforeCredit:'Mikko J. Putkonen · Wikimedia Commons · 2010',s:'Voiman talon eri kerroksissa ovat vaihtuneet ravintolat, pubit ja yökerhot jo vuosikymmenten ajan.',v:[['Voiman Suurravintola','1937–',1937,1959],['Manhattan','noin 1985–',1985,1996],['NiteTrain','1997–',1997,2002],['Love Hotel','NiteTrainin jälkeen',2002,2006],['Fat Lady','myöhempi vaihe',2006,2010],['Sticky Wingers','nykyinen vaihe',2011,2026]]},
{a:'Hatanpään valtatie 1',x:61.49493,y:23.76747,n:'Koskikeskus / Koskenranta',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Koskikeskus%20Tampere%20240725.jpg?width=1200',credit:'Drefer · Wikimedia Commons · 2025',beforeImg:'https://commons.wikimedia.org/wiki/Special:FilePath/Tampere%20-%20Koskikeskus%200469.jpg?width=1200',beforeCredit:'Phyrexian · Wikimedia Commons · 2010',s:'Koskenrannan ravintolahistoria kulkee Fransmannista ja Freetimesta Riversideen, Coloradoon, Sahaan ja Rantaan.',v:[['Fransmanni','1980-luvun loppu',1985,1989],['Freetime','1980-luvun loppu',1985,1989],['Riverside','1990-luvun alku',1990,1994],['Colorado','2000-luvun taite',1998,2003],['Soittoruokala Saha','2000-luvun puoliväli',2004,2009],['Miami','2010-luvun alku',2010,2014],['Jackie Brown','2010-luvun puoliväli',2014,2017],['Ranta','2017–',2017,2026]]}
];

const $=id=>document.getElementById(id);
const q=$('q'),list=$('list'),visible=$('visible'),count=$('count'),explore=$('explore'),maptab=$('maptab'),listtab=$('listtab'),backdrop=$('backdrop'),sheet=$('sheet'),sheetbody=$('sheetbody'),save=$('save'),dockstar=$('dockstar');
let year=null,user=null,selected=0,markers=[],lastFocus=null;
const SK='mtei:v29:saved';
let saved=[];
try{saved=JSON.parse(localStorage.getItem(SK)||'[]')}catch(e){}

const yr=v=>v[1];
const active=p=>year===null?p.v:p.v.filter(v=>v[2]<=year&&v[3]>=year);
const km=p=>{if(!user)return null;const R=6371,dlat=(p.x-user.x)*Math.PI/180,dlon=(p.y-user.y)*Math.PI/180,a=Math.sin(dlat/2)**2+Math.cos(user.x*Math.PI/180)*Math.cos(p.x*Math.PI/180)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(a))};

function rows(){const t=q.value.trim().toLowerCase();let r=D.map((p,i)=>({p,i})).filter(x=>(x.p.a+' '+x.p.n+' '+x.p.v.map(v=>v[0]).join(' ')).toLowerCase().includes(t)&&(year===null||active(x.p).length));if(user)r.sort((a,b)=>(km(a.p)||0)-(km(b.p)||0));return r}
function placePic(p){return p.img?`<div class="placepic"><img src="${p.img}" alt="${p.a}" loading="lazy"><i>${p.refOnly?'PAIKANNUSKUVA':'PAIKKA'}</i></div>`:''}
function mapsUrl(p){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.a+', Tampere, Finland')}`}
function streetUrl(p){return `https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${p.x},${p.y}`}
function whereCard(p){return `<section class="where"><div class="wherevisual">${p.img?`<img src="${p.img}" alt="${p.a}" loading="lazy">`:''}<span class="wherebadge">${p.refOnly?'PAIKANNUSKUVA':'TÄSSÄ PAIKKA ON'}</span></div><h3>Tunnista paikka</h3><p>${p.refOnly?'Kuva auttaa paikantamaan rakennuksen. Sitä ei esitetä nykyjulkisivuna.':'Kuva auttaa tunnistamaan osoitteen nykyisessä kaupunkikuvassa.'}</p><div class="wherebuttons"><a class="street" href="${streetUrl(p)}" target="_blank" rel="noreferrer">Katunäkymä ↗</a><a class="maps" href="${mapsUrl(p)}" target="_blank" rel="noreferrer">Kartta ↗</a></div><small class="wherecredit">${p.credit||''}${p.src?` · <a href="${p.src}" target="_blank" rel="noreferrer">Lähde ↗</a>`:''}</small></section>`}
function beforeNowCard(p){if(!p.beforeImg||!p.img||p.refOnly)return '';return `<section class="beforenow"><div class="bnhead"><span>ENNEN JA NYT</span><h3>Näe muutos yhdellä silmäyksellä</h3><p>Vertailussa ovat aiempi vaihe ja myöhempi kuva samasta osoitteesta.</p></div><div class="bngrid"><figure class="bncard"><div class="bnimg"><img src="${p.beforeImg}" alt="${p.a} ennen" loading="lazy"><i>ENNEN</i></div><figcaption><strong>Aiempi vaihe</strong><small>${p.beforeCredit||''}</small></figcaption></figure><figure class="bncard"><div class="bnimg"><img src="${p.img}" alt="${p.a} myöhemmin" loading="lazy"><i class="now">MYÖHEMMIN</i></div><figcaption><strong>${p.a}</strong><small>${p.credit||''}</small></figcaption></figure></div></section>`}
function setMode(m){explore.className='grid '+(m==='map'?'mapmode':'listmode');maptab.classList.toggle('on',m==='map');listtab.classList.toggle('on',m==='list');setTimeout(()=>map.invalidateSize(),80)}
function draw(){const r=rows();visible.textContent=r.length+' kohdetta';count.textContent=r.length?' '+r.length:'';$('listh').textContent=year===null?'Tampere':'Tampere '+year;list.innerHTML=r.length?r.map(x=>{const names=active(x.p).map(v=>v[0]).slice(-4).join(' · ')||'Ei ajoitettua osumaa';const d=km(x.p);const dist=user?(d!==null&&d<1?Math.round(d*1000)+' m':(d||0).toFixed(1)+' km'):x.p.v.length+' vaihetta';return `<button class="place ${x.i===selected?'on':''}" data-place="${x.i}"><span class="meta"><span>${year===null?'OSOITE':'VUONNA '+year}</span><span>${dist}</span></span>${placePic(x.p)}<b>${x.p.a}</b><small>${names}</small></button>`}).join(''):'<div style="padding:24px;color:var(--muted)"><b>Ei osumia näillä rajauksilla.</b><br>Kokeile lyhyempää hakua tai poista vuosirajaus.</div>';list.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>openPlace(+b.dataset.place));markers.forEach(m=>map.removeLayer(m));markers=r.map(x=>L.circleMarker([x.p.x,x.p.y],{radius:x.i===selected?10:7,color:'#fff',weight:3,fillColor:x.i===selected?'#9e4b3f':'#182326',fillOpacity:1}).addTo(map).bindTooltip(x.p.a).on('click',()=>openPlace(x.i)));updateUrl()}
function updateUrl(){const u=new URL(location.href);u.search='';if(q.value.trim())u.searchParams.set('q',q.value.trim());if(year!==null)u.searchParams.set('vuosi',year);history.replaceState(null,'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams.toString():''))}
function openPlace(i){selected=i;lastFocus=document.activeElement;const p=D[i],vs=active(p);$('position').textContent=`${i+1} / ${D.length}`;sheetbody.innerHTML=`<div class="k">SIJAINTI · TAMPERE</div><h2>${p.a}</h2>${year!==null?`<div class="yearanswer"><small>MITÄ TÄSSÄ OLI VUONNA ${year}?</small><b>${vs.length?vs.map(v=>v[0]).join(' · '):'Ei ajoitettua tietoa'}</b></div>`:''}${whereCard(p)}${beforeNowCard(p)}<p class="summary">${p.s}</p><div class="timeline">${(year===null?p.v:vs).map(v=>`<div class="it"><b>${v[0]}</b><span>${yr(v)}</span></div>`).join('')||'Ei ajoitettua tietoa tästä vuodesta.'}</div>`;save.textContent=saved.includes(i)?'★ Tallennettu':'☆ Tallenna kierrokselle';backdrop.classList.add('open');document.body.style.overflow='hidden';sheet.focus();map.flyTo([p.x,p.y],16,{duration:.45});draw()}
function closeSheet(){backdrop.classList.remove('open');document.body.style.overflow='';if(lastFocus)lastFocus.focus()}
function step(d){openPlace((selected+d+D.length)%D.length)}
function persist(){localStorage.setItem(SK,JSON.stringify(saved));renderTour();save.textContent=saved.includes(selected)?'★ Tallennettu':'☆ Tallenna kierrokselle'}
function toggleSave(){saved=saved.includes(selected)?saved.filter(i=>i!==selected):[...saved,selected];persist()}
function renderTour(){dockstar.textContent=String(saved.length||'☆');$('tourh').textContent=saved.length?saved.length+' tallennettua paikkaa':'Tallenna kiinnostavat paikat';$('tourp').textContent=saved.length?'Rakenna niistä oma kävelykierros tai jatka selaamista. Tallennukset jäävät tähän selaimeen.':'Tähdellä tallennetut kohteet jäävät vain tähän selaimeen. Kirjautumista ei tarvita.';$('tourlist').innerHTML=saved.map((i,n)=>`<div class="touritem"><small>${String(n+1).padStart(2,'0')} · ${D[i].a}</small><b>${D[i].n}</b></div>`).join('');if(saved.length>1){const pts=saved.map(i=>D[i]),first=pts[0],last=pts[pts.length-1],wp=pts.slice(1,-1).map(p=>p.x+','+p.y).join('|');const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('origin',first.x+','+first.y);u.searchParams.set('destination',last.x+','+last.y);u.searchParams.set('travelmode','walking');if(wp)u.searchParams.set('waypoints',wp);$('touractions').innerHTML=`<a class="btn light" target="_blank" rel="noreferrer" href="${u}">Avaa kävelyreitti ↗</a><button class="btn light" id="cleartour">Tyhjennä</button>`;$('cleartour').onclick=()=>{saved=[];persist()}}else $('touractions').innerHTML=''}
function syncYears(){$('read').textContent=year??'Kaikki';$('timeh').textContent=year===null?'Valitse vuosi':'Tampere '+year;document.querySelectorAll('.years button').forEach(b=>b.classList.toggle('on',year===null?b.dataset.y==='all':+b.dataset.y===year));if(year!==null)$('range').value=year}

const map=L.map('map',{zoomControl:false}).setView([61.4981,23.7608],14);
L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);

q.oninput=()=>{setMode('list');draw()};
$('clear').onclick=()=>{q.value='';draw();q.focus()};
$('random').onclick=()=>openPlace(Math.floor(Math.random()*D.length));
$('near').onclick=()=>{setMode('map');const m=$('locmsg');if(!navigator.geolocation){m.textContent='Selaimesi ei tue sijaintia. Haku toimii silti.';return}m.textContent='Haetaan sijaintia…';navigator.geolocation.getCurrentPosition(pos=>{user={x:pos.coords.latitude,y:pos.coords.longitude};m.textContent='Lähimmät Tampereen kohteet järjestettiin etäisyyden mukaan. Sijaintia ei tallenneta.';const r=rows();if(r.length){selected=r[0].i;map.flyTo([r[0].p.x,r[0].p.y],16)}draw();$('explore').scrollIntoView({behavior:'smooth'})},()=>m.textContent='Sijaintia ei saatu käyttöön. Voit hakea osoitteella tai nimellä.',{enableHighAccuracy:true,timeout:8000})};
$('range').oninput=e=>{year=+e.target.value;syncYears();draw()};
document.querySelectorAll('.years button').forEach(b=>b.onclick=()=>{year=b.dataset.y==='all'?null:+b.dataset.y;syncYears();draw()});
maptab.onclick=()=>setMode('map');listtab.onclick=()=>setMode('list');
$('gclose').onclick=()=>document.getElementById('guide')?.classList.remove('show');
$('gsearch').onclick=()=>{q.focus();window.scrollTo({top:0,behavior:'smooth'})};
$('gnear').onclick=()=>$('near').click();
$('g95').onclick=()=>{year=1995;syncYears();draw();$('time').scrollIntoView({behavior:'smooth'})};
$('close').onclick=closeSheet;
backdrop.onmousedown=e=>{if(e.target===backdrop)closeSheet()};
$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);save.onclick=toggleSave;
$('share').onclick=async()=>{const url=location.origin+location.pathname+'?paikka='+encodeURIComponent(D[selected].a);try{if(navigator.share)await navigator.share({title:D[selected].a+' – Mitä tässä ennen oli?',url});else{await navigator.clipboard.writeText(url);const t=document.createElement('div');t.className='toast';t.textContent='Linkki kopioitu';document.body.append(t);setTimeout(()=>t.remove(),1800)}}catch(e){}};
$('docksearch').onclick=()=>{q.focus();window.scrollTo({top:0,behavior:'smooth'})};
$('docknear').onclick=()=>$('near').click();
window.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(e.key==='/'&&!typing){e.preventDefault();q.focus()}if(e.key==='Escape'&&backdrop.classList.contains('open'))closeSheet();if(!typing&&backdrop.classList.contains('open')){if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)}});
const params=new URLSearchParams(location.search);
if(params.get('q'))q.value=params.get('q');
if(/^\d{4}$/.test(params.get('vuosi')||''))year=+params.get('vuosi');
if(params.get('paikka')){const i=D.findIndex(p=>p.a===params.get('paikka'));if(i>=0)setTimeout(()=>openPlace(i),300)}
try{if(!localStorage.getItem('mtei:v29:guide')){$('guide').classList.add('show');localStorage.setItem('mtei:v29:guide','1')}}catch(e){}
syncYears();renderTour();draw();
